models/Search.py
from models import User
from db import db

#search model to be stored in analytics database 
class Search(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id')) 
    search_query = db.Column(db.String(200))
    search_result = db.Column(db.Text)

    #define relationship with user model
    user = db.relationship('User', backref = 'searches')

models/User.py
from flask_login import UserMixin
from db import db

#set up user model to be stored in user database  
class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(100), unique=True)
    password = db.Column(db.String(100))

app.py
from flask import Flask
from db import db
from dotenv import load_dotenv
import os
from auth import auth as auth_blueprint
from flask_login import LoginManager
from models.User import User

load_dotenv()

app = Flask(__name__)
app.register_blueprint(auth_blueprint)


app.config['SECRET_KEY'] = os.getenv('SECRET_KEY')
#debugging for secret key 
print(f"Secret Key: {app.config['SECRET_KEY']}")
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///db.sqlite3'


db.init_app(app)

login_manager = LoginManager()
login_manager.init_app(app)

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

auth.py
#imports
from flask import redirect, render_template, request, session, url_for, Blueprint
from db import db
from models.User import User
#for password hash 
from werkzeug.security import generate_password_hash, check_password_hash
#for login functionality 
from flask_login import LoginManager, UserMixin, login_user, login_required, logout_user, current_user

#set up Blueprint
auth = Blueprint('auth', __name__)

#registration route 
@auth.route('/register', methods=['GET', 'POST'])
def register():
    already_user = None
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')

        #check if user already exists
        existing_user = User.query.filter_by(username=username).first()
        if existing_user:
            print ("User already exists, please go to Login page")
            already_user = True
            return render_template('register.html', message="User already exists, please go to Login page")
        else:
            already_user = False
        
        hashed_password = generate_password_hash(password, method='pbkdf2:sha256')

        new_user = User(username=username, password=hashed_password)
        db.session.add(new_user)
        db.session.commit()
        return redirect(url_for('auth.login', message="Registration Successful", already_user = already_user))

    return render_template('register.html', already_user = already_user, current_user = current_user)

#login route
@auth.route('/login', methods=['GET', 'POST'])
def login():
    login_failed = None
    login_attempted = False
    if request.method == 'POST':
        login_attempted = True
        username = request.form.get('username')
        password = request.form.get('password')

        user = User.query.filter_by(username=username).first()
        if not user or not check_password_hash(user.password, password):
            login_failed = True
        else:
            login_failed = False
            #session['username'] = user.username
            login_user(user)
        
        return render_template('index.html', login_failed=login_failed, login_attempted = login_attempted)

    return render_template('index.html', login_failed=login_failed, login_attempted = login_attempted)

#logout route 
@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

routes.py
from flask import render_template, request, redirect, url_for, session
from app import app
from db import db
from models import User, Search
import requests
from flask_login import current_user




@app.route('/')
def home():
    print("rendering home.html")
    return render_template('index.html', current_user = current_user)



@app.route('/search', methods=['GET'])
def search():
    username = session.get('username')
    search_query = request.args.get('search')
    #added print statements for debugging
    print(f'Search Query: {search_query}')  
    
    try:
        response = requests.get(f'https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/name/{search_query}/JSON')
        response.raise_for_status() 
    except requests.exceptions.RequestException as e:
        print(f'An error occurred: {e}')
        response = None

    compound_info = response.json() if response and response.status_code == 200 else None
    compound_data = {}

    if compound_info:
        compound = compound_info['PC_Compounds'][0]
        props = compound['props']

    # point of improvement - I want to recreate this for loop for easier readability 
    #      property_map = {
    #         ('Allowed', 'IUPAC Name'): 'iupac_name', ....  }
    #     for prop in props:
    #         key = (prop['urn'].get('name', ''), prop['urn'].get('label', '')) ...
    
    

        # Extracting the IUPAC name, charge, molecular weight, compound complexity 
        for prop in props:
            if 'name' in prop['urn'] and prop['urn']['name'] == 'Allowed' and prop['urn']['label'] == 'IUPAC Name':
                compound_data['iupac_name'] = prop['value']['sval']
            elif 'label' in prop['urn'] and prop['urn']['label'] == 'Molecular Weight':
                compound_data['molecular_weight'] = prop['value']['sval'] + ' g/mol'
            elif 'label' in prop['urn'] and prop['urn']['label'] == 'Compound Complexity':
                compound_data['compound_complexity'] = prop['value']['fval']
                compound_data['complexity_datatype'] = prop['urn']['datatype']
            elif 'name' in prop['urn'] and prop['urn']['name'] == 'Hydrogen Bond Donor':
                compound_data['hydrogen_bond_donor'] = prop['value']['ival']
                compound_data['donor_datatype'] = prop['urn']['datatype']
            elif 'name' in prop['urn'] and prop['urn']['name'] == 'Hydrogen Bond Acceptor':
                compound_data['hydrogen_bond_acceptor'] = prop['value']['ival']
                compound_data['acceptor_datatype'] = prop['urn']['datatype']
            elif 'label' in prop['urn'] and prop['urn']['label'] == 'SMILES' and prop['urn']['name'] == 'Isomeric':
                compound_data['smiles_isomeric'] = prop['value']['sval']

        compound_data['charge'] = compound['charge']


    # point of improvement: I want to be able to create a relationship with User and Search for an analytics database 
        # search_result = Search(user_id=username, search_query=search_query, search_result=str(compound_data))
        # db.session.add(search_result)
        # db.session.commit()


        return render_template('compound_info.html', search_query=search_query, compound_info=compound_data, username = username, current_user = current_user)
    else:
        return render_template('return.html')

templates/compound_info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css" rel="stylesheet">
    <title>Compound Information</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='home.css') }}">
    <title>Document</title>
</head>
<body class = "compound_info">
    <nav>
        {% if current_user.is_authenticated %}
        <a href="{{ url_for('auth.logout') }}">Logout</a>
        {% else %}
        <a href="{{ url_for('auth.login') }}">Login</a>
        <a href="{{ url_for('auth.register')}}">Register Here</a>
        {% endif %}
        <a href="https://pubchem.ncbi.nlm.nih.gov/">Visit PubChem </a>
         <a href="https://opendata.oraclecloud.com/ords/r/opendata/opendata/details-cs?data_set_id=2&cs=1LWgWbAhOtwy7imm9IuewSzvgR1Teas0Yi7VSjvARvH-825i7ypPgpWZ8lS1cjc9LvsrQCYa34wH9kBSbG2PIig">ZINC 22 </a>
    </nav>
    <div id = "username2"> 
        <h5> <strong> Username: </strong> {{ current_user.username }}</h5>
    </div>
    <br>
    <br>
    <br>
    <h6> Make Another Search: </h6>
    <div id="search-container">
        <form id = "search-bar" method="GET" action="/search">
            <input type="text" name="search" placeholder="Search PubChem" {% if not current_user.is_authenticated %}disabled{% endif %}>
            <input type="submit" value="Search" {% if not current_user.is_authenticated %}disabled{% endif %}> 
        </form>
    </div>
    <div class  ="compounds">
    <h1>Compound Information for {{ search_query }}</h1>
    <p><strong>IUPAC Name:</strong> {{ compound_info.iupac_name }}</p>
    <p><strong>Molecular Weight:</strong> {{ compound_info.molecular_weight }}</p>
    <p><strong>Charge:</strong> {{ compound_info.charge }}</p>
    <p><strong>Compound Complexity:</strong> {{ compound_info.compound_complexity }}</p>
    <p><strong>Hydrogen Bond Donor, Acceptors </strong> {{ compound_info.hydrogen_bond_donor }} , {{ compound_info.hydrogen_bond_acceptor }}</p>
    <p><strong>Isomeric SMILES Configuration </strong> {{ compound_info.smiles_isomeric }} </p>
    

    <script src="https://unpkg.com/react@17/umd/react.development.js"></script>
    <script src="https://unpkg.com/react-dom@17/umd/react-dom.development.js"></script>   
    <script src="static/search.js"></script>
</body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css" rel="stylesheet">
    <title>Home Page</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='home.css') }}">
</head>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
<body>
    <nav>
        <a href="{{ url_for('auth.login') }}">Login</a>
        <a href="{{ url_for('auth.register')}}">Register Here</a>
        <a href="https://pubchem.ncbi.nlm.nih.gov/">Visit PubChem </a>
    </nav>
    <div id="login_reqd">
        <h3>Please Login before searching: </h3>
    <br>
    </div>

    <form id="login" action="/login" method="POST">
        <div class="form-group">
            <label for="username">Username:</label>
            <input type="text" placeholder="Enter Username" class="form-control" id="username" name="username" required> <br> 
        </div>
        <div class="form-group">
            <label for="password">Password:</label>
            <input type="password" placeholder="Enter Password" class="form-control" id="password" name="password" required> <br>
        </div>
        <div class="form-group">
            <input type="submit" class="btn btn-primary" value="Login">
        </div>
        {% if login_failed is not none %}
        {% if login_failed %}
            <div class="mt-2">
                <span class="bi bi-x-circle-fill text-danger"> Login failed</span>
            </div>
        {% else %}
            <div class="mt-2">
                <span class="bi bi-check-circle-fill text-success"> Login successful</span>
            </div>
        {% endif %}
    {% endif %}
        
    </form>
    <h3> Search Database Here: </h3>
    <div id="search-container">
        <form id = "search-bar" method="GET" action="/search">
            <input type="text" name="search" placeholder="Search">
            <input type="submit" value="Search"> 
        </form>
    </div>
     <script src="https://unpkg.com/react@17/umd/react.development.js"></script>
    <script src="https://unpkg.com/react-dom@17/umd/react-dom.development.js"></script>   
    <script src="static/search.js"></script>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css" rel="stylesheet">
    <title>Lea's OCI Proj</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='home.css') }}">
</head>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
<body>
    <nav>
        {% if current_user.is_authenticated %}
        <a href="{{ url_for('auth.logout') }}">Logout</a>
        {% else %}
        <a href="{{ url_for('auth.login') }}">Login</a>
        <a href="{{ url_for('auth.register')}}">Register Here</a>
        {% endif %}
        <a href="https://pubchem.ncbi.nlm.nih.gov/">Visit PubChem </a>
         <a href="https://opendata.oraclecloud.com/ords/r/opendata/opendata/details-cs?data_set_id=2&cs=1LWgWbAhOtwy7imm9IuewSzvgR1Teas0Yi7VSjvARvH-825i7ypPgpWZ8lS1cjc9LvsrQCYa34wH9kBSbG2PIig">ZINC 22 </a>
    
    </nav>
    <div id="login_reqd">
        <h3>Please Login before searching: </h3>
    <br>
    </div>

    <form id="login" action="/login" method="POST">
        <div class="form-group">
            <label for="username">Username:</label>
            <input type="text" placeholder="Enter Username" class="form-control" id="username" name="username" required> <br> 
        </div>
        <div class="form-group">
            <label for="password">Password:</label>
            <input type="password" placeholder="Enter Password" class="form-control" id="password" name="password" required> <br>
        </div>
        <div class="form-group">
            <input type="submit" class="btn btn-primary" value="Login">
        </div>
    {% if login_attempted %}
        {% if login_failed %}
            <div class="mt-2">
                <span class="bi bi-x-circle-fill text-danger"> Login failed</span>
            </div>
        {% else %}
            <div class="mt-2">
                <span class="bi bi-check-circle-fill text-success"> Login successful</span>
            </div>
        {% endif %}
    {% endif %}
        
    </form>
    <h3> Search Database Here: </h3>
    <div id="search-container">
        <form id = "search-bar" method="GET" action="/search">
            <input type="text" name="search" placeholder="Search PubChem" {% if not current_user.is_authenticated %}disabled{% endif %}>
            <input type="submit" value="Search" {% if not current_user.is_authenticated %}disabled{% endif %}> 
        </form>
    </div>
     <script src="https://unpkg.com/react@17/umd/react.development.js"></script>
    <script src="https://unpkg.com/react-dom@17/umd/react-dom.development.js"></script>   
    <script src="static/search.js"></script>
</body>
</html>

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='home.css') }}">
</head>
<body>
    <nav>
        <a href="{{ url_for('auth.login') }}">Login</a>
        <a href="{{ url_for('auth.register')}}">Register Here</a>
        <a href="https://pubchem.ncbi.nlm.nih.gov/">Visit PubChem </a>
    </nav>
    <h2> Register Here: </h2>
    <form id ="registration" action="/register" method="POST">
        <label for="username">Username:</label>
        <input type="text" placeholder="Enter Username" id="username" name="username">
        <label for="password">Password:</label>
        <input type="password" placeholder="Enter Password" id="password" name="password">
        <input type="submit" value="Register">
    </form>
    {% if message %}
        {% if message == "Registration successful" %}
            <p style="color:green;">{{ message }} ✔️</p>
        {% else %}
            <p style="color:red;">{{ message }} ❌</p>
        {% endif %}
    {% endif %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://unpkg.com/react@17/umd/react.development.js"></script>
    <script src="https://unpkg.com/react-dom@17/umd/react-dom.development.js"></script>
</body>
</html>

templates/return.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Return to Homepage</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='home.css') }}">
</head>
<body>
    <nav>
        <a href="{{ url_for('auth.login') }}">Login</a>
        <a href="{{ url_for('auth.register')}}">Register Here</a>
        <a href="https://pubchem.ncbi.nlm.nih.gov/">Visit PubChem </a>
        <a href="https://opendata.oraclecloud.com/ords/r/opendata/opendata/details-cs?data_set_id=2&cs=1LWgWbAhOtwy7imm9IuewSzvgR1Teas0Yi7VSjvARvH-825i7ypPgpWZ8lS1cjc9LvsrQCYa34wH9kBSbG2PIig">ZINC 22 </a>
    </nav>
    <div id="login_reqd">
        <h3>No Compound Information Found, Please Try Again </h3>
    <br>
    </div>
    <div id = "return">
        <a href="{{ url_for('auth.login') }}" class = "button"> Return to Homepage </a>
    </div>
</body>
</html>